In [1]:
import plotly.express as px
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    "Month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    "Sales": [120, 150, 170, 160, 210, 250]
})

In [3]:
df

  Month  Sales
0   Jan    120
1   Feb    150
2   Mar    170
3   Apr    160
4   May    210
5   Jun    250

In [4]:
px.line(df, x='Month', y='Sales', title='Monthly Sales', markers=True)

In [5]:
df = pd.DataFrame({
    "Course": ["Python", "Data Science", "GenAI", "DevOps"],
    "Students": [300, 220, 420, 180]
})

In [7]:
px.bar(df, x="Course", y="Students", title="Student Enrollment")

In [10]:
# Horizontal Bar Chart
px.bar(df, x="Students", y="Course", title="Student Enrollment", orientation='h')

In [11]:
df = px.data.iris()

In [12]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [13]:
px.scatter(df, x="sepal_width", y="sepal_length")

In [16]:
df = px.data.gapminder().query("year == 2007")

In [17]:
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [18]:
px.scatter(df, x="gdpPercap", y="lifeExp", color="country")

In [24]:
df3 = px.data.gapminder().query("year == 2007 & year == 2009")