In [1]:
import pandas as pd

In [98]:
original_df = pd.read_csv('dirty_customer_data.csv')

In [99]:
# Shape of original df
original_df.shape

(112, 7)

In [100]:
# copy of original_df
df = original_df.copy()

In [101]:
# First 5 rows of the df
df.head()

,customer_id,name,age,city,email,purchase_amount,rating
0,C001,rahul sharma,25,pune,RAHUL@EMAIL.COM,1500,4.5
1,C002,PRIYA PATEL,22,MUMBAI,priya@email.com,2200,4
2,C003,Amit Shah,twenty,Ahmedabad,amit@email.com,1800,4.2
3,C004,Neha Mehta,28,delhi,neha@email.com,NaN,4.7
4,C005,rohit verma,30,PUNE,rohit@email.com,2500,NaN

In [102]:
# Checking the data types of each column
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      112 non-null    str
 1   name             112 non-null    str
 2   age              112 non-null    str
 3   city             112 non-null    str
 4   email            112 non-null    str
 5   purchase_amount  109 non-null    str
 6   rating           108 non-null    str
dtypes: str(7)
memory usage: 6.3 KB

In [103]:
# Detecting missing values
df.isnull()

     customer_id   name    age   city  email  purchase_amount  rating
0          False  False  False  False  False            False   False
1          False  False  False  False  False            False   False
2          False  False  False  False  False            False   False
3          False  False  False  False  False             True   False
4          False  False  False  False  False            False    True
..           ...    ...    ...    ...    ...              ...     ...
107        False  False  False  False  False            False   False
108        False  False  False  False  False            False   False
109        False  False  False  False  False            False   False
110        False  False  False  False  False            False    True
111        False  False  False  False  False            False   False

[112 rows x 7 columns]

In [104]:
# Count of missing values in each column
df.isnull().sum()

customer_id        0
name               0
age                0
city               0
email              0
purchase_amount    3
rating             4
dtype: int64

In [105]:
# Dropping rows with missing values
df.dropna(inplace=True)

# Count of missing values in each column after dropping rows with missing values
df.isnull().sum()

customer_id        0
name               0
age                0
city               0
email              0
purchase_amount    0
rating             0
dtype: int64

In [106]:
# Detecting duplicate rows in the df
df.duplicated()

0      False
1      False
2      False
5      False
6      False
       ...
106    False
107    False
108    False
109    False
111    False
Length: 105, dtype: bool

In [107]:
# Count of duplicate rows in the df
df.duplicated().sum()

np.int64(2)

In [108]:
# Deleting duplicate rows in the df
df.drop_duplicates(inplace=True)

# Count of duplicate rows in the df after deleting duplicates
df.duplicated().sum()

np.int64(0)

In [109]:
# Checking the data types of each column
df.dtypes

customer_id        str
name               str
age                str
city               str
email              str
purchase_amount    str
rating             str
dtype: object

In [110]:
# Correcting data types of columns
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['purchase_amount'] = pd.to_numeric(df['purchase_amount'], errors='coerce')
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

In [111]:
# Checking the data types of each column after correcting data types
df.dtypes

customer_id            str
name                   str
age                float64
city                   str
email                  str
purchase_amount    float64
rating             float64
dtype: object

In [112]:
# Checking for any missing values after correcting data types
df.isnull().sum()

customer_id         0
name                0
age                10
city                0
email               0
purchase_amount     1
rating              2
dtype: int64

In [113]:
# Filling age column missing values with mean
df['age'] = df['age'].fillna(df['age'].mean())

# Filling purchase_amount column missing values with median
df['purchase_amount'] = df['purchase_amount'].fillna(df['purchase_amount'].median())

# Filling rating column missing values with mode
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

In [114]:
# Checking for missing values after filling missing values
df.isnull().sum()

customer_id        0
name               0
age                0
city               0
email              0
purchase_amount    0
rating             0
dtype: int64

In [115]:
# First 5 rows of name column before cleaning
df['name'].head()

0      rahul sharma
1         PRIYA PATEL
2           Amit Shah
5         Sneha Iyer
6         ARJUN REDDY
Name: name, dtype: str

In [116]:
# Cleaning the name column by removing leading and trailing spaces and converting to title case
df['name'] = df['name'].str.strip().str.title()

# First 5 rows of name column after cleaning
df['name'].head()

0    Rahul Sharma
1     Priya Patel
2       Amit Shah
5      Sneha Iyer
6     Arjun Reddy
Name: name, dtype: str

In [117]:
# First 5 rows of city column before cleaning
df['city'].head()

0          pune
1        MUMBAI
2     Ahmedabad
5     bengaluru
6     Hyderabad
Name: city, dtype: str

In [118]:
# Cleaning the city column by removing leading and trailing spaces and converting to uppercase
df['city'] = df['city'].str.strip().str.upper()

# First 5 rows of city column after cleaning
df['city'].head()

0         PUNE
1       MUMBAI
2    AHMEDABAD
5    BENGALURU
6    HYDERABAD
Name: city, dtype: str

In [119]:
# First 5 rows of email column before cleaning
df['email'].head()

0      RAHUL@EMAIL.COM
1     priya@email.com
2       amit@email.com
5      sneha@email.com
6      arjun@email.com
Name: email, dtype: str

In [120]:
# Cleaning the email column by removing leading and trailing spaces and converting to lowercase
df['email'] = df['email'].str.strip().str.lower()

# First 5 rows of email column after cleaning
df['email'].head()

0    rahul@email.com
1    priya@email.com
2     amit@email.com
5    sneha@email.com
6    arjun@email.com
Name: email, dtype: str

In [121]:
# Checking for unique values in city column
df['city'].unique()

<StringArray>
[      'PUNE',     'MUMBAI',  'AHMEDABAD',  'BENGALURU',  'HYDERABAD',
      'KOCHI',     'JAIPUR', 'CHANDIGARH',      'DELHI',    'LUCKNOW',
      'PATNA',     'BOMBAY',    'CHENNAI',      'SURAT',      'NOIDA',
    'KOLKATA',     'NASHIK',     'BHOPAL',     'KANPUR',   'AMRITSAR',
    'GURGAON',     'SHIMLA',     'RANCHI',   'VARANASI',     'NAGPUR',
   'DEHRADUN',     'INDORE']
Length: 27, dtype: str

Above we can see that there is mumbai as well as bombay, which is the same city. We will replace bombay with mumbai.

In [122]:
# Replacing inconsistent city names with correct ones
df['city'] = df['city'].replace({'BOMBAY': 'MUMBAI'})

# Checking for unique values in city column after replacing inconsistent city names
df['city'].unique()

<StringArray>
[      'PUNE',     'MUMBAI',  'AHMEDABAD',  'BENGALURU',  'HYDERABAD',
      'KOCHI',     'JAIPUR', 'CHANDIGARH',      'DELHI',    'LUCKNOW',
      'PATNA',    'CHENNAI',      'SURAT',      'NOIDA',    'KOLKATA',
     'NASHIK',     'BHOPAL',     'KANPUR',   'AMRITSAR',    'GURGAON',
     'SHIMLA',     'RANCHI',   'VARANASI',     'NAGPUR',   'DEHRADUN',
     'INDORE']
Length: 26, dtype: str

In [125]:
# Converting data types of age and purchase_amount columns to integer
df['age'] = df['age'].astype(int)
df['purchase_amount'] = df['purchase_amount'].astype(int)

# Checking data types of all columns after converting data types
df.dtypes

customer_id            str
name                   str
age                  int64
city                   str
email                  str
purchase_amount      int64
rating             float64
dtype: object

In [126]:
# Comparing the shape of original df and cleaned df
print(f"Shape of original df: {original_df.shape}")
print(f"Shape of cleaned df: {df.shape}")

Shape of original df: (112, 7)
Shape of cleaned df: (103, 7)

In [127]:
# Saving the cleaned df to a new CSV file
df.to_csv('cleaned_customer_data.csv', index=False)