In [3]:
# Sample sales data for sales.txt
sales_data = """order_id,product,quantity,price,city
101,Laptop,1,65000,Bangalore
102,Mouse,2,1200,Delhi
103,Keyboard,1,2500,Pune
104,Monitor,2,18000,Mumbai
105,Headphones,3,3500,Chennai
106,Laptop,1,72000,Delhi
107,Mouse,5,1000,Pune
108,Keyboard,2,3000,Bangalore
109,Monitor,1,22000,Hyderabad
110,Tablet,1,35000,Mumbai
111,Headphones,2,4500,Pune
112,Laptop,2,68000,Chennai
113,Mouse,3,900,Delhi
114,Keyboard,1,2800,Mumbai
115,Monitor,2,19500,Bangalore
116,Tablet,2,32000,Delhi
117,Headphones,1,5000,Hyderabad
118,Laptop,1,75000,Pune
119,Mouse,4,1100,Mumbai
120,Keyboard,3,2700,Chennai
121,Monitor,1,21000,Delhi
122,Tablet,1,38000,Bangalore
123,Headphones,2,4200,Pune
124,Laptop,1,69000,Mumbai
125,Mouse,6,950,Hyderabad
126,Keyboard,2,3200,Delhi
127,Monitor,1,24000,Pune
128,Tablet,2,36000,Chennai
129,Headphones,3,3800,Bangalore
130,Laptop,1,71000,Hyderabad
131,Mouse,2,1300,Pune
132,Keyboard,1,2900,Mumbai
133,Monitor,2,20500,Chennai
134,Tablet,1,40000,Delhi
135,Headphones,2,4600,Bangalore
"""

In [4]:
# Write the sales data to a text file
with open('sales.txt', 'w') as file:
    file.write(sales_data)

In [5]:
# Read the sales data from the text file 
with open('sales.txt', 'r') as file:
    sales_records = file.readlines()

# Print the sales records
for record in sales_records:
    print(record.strip())

order_id,product,quantity,price,city
101,Laptop,1,65000,Bangalore
102,Mouse,2,1200,Delhi
103,Keyboard,1,2500,Pune
104,Monitor,2,18000,Mumbai
105,Headphones,3,3500,Chennai
106,Laptop,1,72000,Delhi
107,Mouse,5,1000,Pune
108,Keyboard,2,3000,Bangalore
109,Monitor,1,22000,Hyderabad
110,Tablet,1,35000,Mumbai
111,Headphones,2,4500,Pune
112,Laptop,2,68000,Chennai
113,Mouse,3,900,Delhi
114,Keyboard,1,2800,Mumbai
115,Monitor,2,19500,Bangalore
116,Tablet,2,32000,Delhi
117,Headphones,1,5000,Hyderabad
118,Laptop,1,75000,Pune
119,Mouse,4,1100,Mumbai
120,Keyboard,3,2700,Chennai
121,Monitor,1,21000,Delhi
122,Tablet,1,38000,Bangalore
123,Headphones,2,4200,Pune
124,Laptop,1,69000,Mumbai
125,Mouse,6,950,Hyderabad
126,Keyboard,2,3200,Delhi
127,Monitor,1,24000,Pune
128,Tablet,2,36000,Chennai
129,Headphones,3,3800,Bangalore
130,Laptop,1,71000,Hyderabad
131,Mouse,2,1300,Pune
132,Keyboard,1,2900,Mumbai
133,Monitor,2,20500,Chennai
134,Tablet,1,40000,Delhi
135,Headphones,2,4600,Bangalore

In [6]:
# Imort the pandas library
import pandas as pd

In [7]:
# Read the sales data from the text file into a pandas DataFrame
df = pd.read_csv('sales.txt')

# Display first five rows of the DataFrame
df.head()

   order_id     product  quantity  price       city
0       101      Laptop         1  65000  Bangalore
1       102       Mouse         2   1200      Delhi
2       103    Keyboard         1   2500       Pune
3       104     Monitor         2  18000     Mumbai
4       105  Headphones         3   3500    Chennai

In [8]:
# type of the DataFrame
type(df)

pandas.DataFrame

In [9]:
# Shape of the DataFrame
df.shape

(35, 5)

In [10]:
# DataFrame information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  35 non-null     int64
 1   product   35 non-null     str
 2   quantity  35 non-null     int64
 3   price     35 non-null     int64
 4   city      35 non-null     str
dtypes: int64(3), str(2)
memory usage: 1.5 KB

In [11]:
# Calculate Revenue
df['revenue'] = df['quantity'] * df['price']
df.head()

   order_id     product  quantity  price       city  revenue
0       101      Laptop         1  65000  Bangalore    65000
1       102       Mouse         2   1200      Delhi     2400
2       103    Keyboard         1   2500       Pune     2500
3       104     Monitor         2  18000     Mumbai    36000
4       105  Headphones         3   3500    Chennai    10500

In [12]:
# Find total revenue.
total_revenue = df['revenue'].sum()
total_revenue

np.int64(1025000)

In [14]:
# Find average order value.
average_order_value = round(df['revenue'].mean(), 2)
average_order_value

np.float64(29285.71)

In [ ]:
# Find highest-value order using .loc and .idxmax() methods
highest_value_order = df.loc[df['revenue'].idxmax()]
highest_value_order

order_id        112
product      Laptop
quantity          2
price         68000
city        Chennai
revenue      136000
Name: 11, dtype: object

In [17]:
# Find the order with the highest revenue without using .loc and .idxmax() methods
df[df['revenue'] == df['revenue'].max()]

    order_id product  quantity  price     city  revenue
11       112  Laptop         2  68000  Chennai   136000

In [18]:
# Find lowest-value order using .loc and .idxmin() methods
lowest_value_order = df.loc[df['revenue'].idxmin()]
lowest_value_order

order_id      102
product     Mouse
quantity        2
price        1200
city        Delhi
revenue      2400
Name: 1, dtype: object

In [19]:
# Find the order with the lowest revenue without using .loc and .idxmin() methods
df[df['revenue'] == df['revenue'].min()]

   order_id product  quantity  price   city  revenue
1       102   Mouse         2   1200  Delhi     2400

In [21]:
# Find revenue product-wise.
product_revenue = df.groupby('product')['revenue'].sum()
product_revenue

product
Headphones     53500
Keyboard       28700
Laptop        488000
Monitor       183000
Mouse          22800
Tablet        249000
Name: revenue, dtype: int64

In [22]:
# Find revenue city-wise.
city_revenue = df.groupby('city')['revenue'].sum()
city_revenue

city
Bangalore    168600
Chennai      267600
Delhi        208500
Hyderabad    103700
Mumbai       150100
Pune         126500
Name: revenue, dtype: int64

In [24]:
# Save processed data to a new CSV file
df.to_csv('sales_report.csv', index=False)